- debug: msg="Test starts with {{ mode }} mode"
#- name: Minio healthchecks pass
#    uri:
#      url: http://localhost:8500/v1/health/connect/minio
#      method: GET
#      body_format: json
#      return_content: true
#    retries: 10
#    delay: 10
#    register: minio_check
#    until: "minio_check.json.Requests.request_status == 'COMPLETED' or ambari_create_cluster_check.json.Requests.request_status == 'ABORTED'"
#    failed_when: "minio_check.json.Requests.request_status == 'ABORTED'"
#    when: "minio_check.json is defined"