- debug: msg="Test starts with {{ mode }} mode"
- name: Minio healthchecks pass
  uri:
#    curl -G -v localhost:8500/v1/health/checks/minio --data-urlencode 'filter=(Status=="passing")'
    url: http://localhost:8500/v1/health/checks/minio?filter={{ '(Status=="passing")' | urlencode }}
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result
  retries: 10
  delay: 15
  until: result.json | length == 2
- name: Response body
  debug: msg="Here {{ (result.json) }} "
