name: CI/CD

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, edited, closed]
    paths:
      - 'packer/**'
jobs:
  build:
    # Macos includes virtualbox and vagrant.
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run make build
        run: make build

      - name: Make box available as artifact
        uses: actions/upload-artifact@v2
        with:
          name: vagrantbox
          path: packer/output-fun/package.box

  test:
    needs: build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: vagrantbox
          path: packer/output-fun

      - name: Run make test
        run: make test

  release-prerequisites:
    if: contains(github.event.pull_request.labels.*.name, 'major')||contains(github.event.pull_request.labels.*.name, 'minor')||contains(github.event.pull_request.labels.*.name, 'patch')
    runs-on: macos-latest
    outputs:
      bump: ${{ steps.bump.outputs.match }}
      next_version: ${{ steps.next_version.outputs.version }}
      current_version: ${{ fromJson(steps.current_version.outputs.output).data.current_version.version }}
    steps:        # Runs make test
      - id: current_version
        uses: satak/webrequest-action@v1.2.3
        with:
          url: https://app.vagrantup.com/api/v1/box/zhenik/fun
          method: GET

      - name: Require PR label (major/minor/patch)
        id: bump
        uses: zwaldowski/match-label-action@v1
        with:
          allowed: major,minor,patch

      - id: next_version
        uses: zwaldowski/semver-release-action@v1
        with:
          dry_run: true
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print current version of vagrantbox
        run: |
          echo "Current version on vagrant cloud: ${{ fromJson(steps.current_version.outputs.output).data.current_version.version }}"
          echo "New version about to be pushed to vagrant cloud: ${{ steps.next_version.outputs.version }}"

  release:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    needs:
      - test
      - release-prerequisites

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get vagrantbox artifact
        uses: actions/download-artifact@v2
        with:
          name: vagrantbox
          path: packer/output-fun

      - name: Upload and release vagrantbox on vagrant cloud
        env:
          VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
        run: |
          vagrant cloud publish --release --force zhenik/fun ${{ needs.release-prerequisites.outputs.next_version }} virtualbox packer/output-fun/package.box

      - name: Release code on github
        uses: zwaldowski/semver-release-action@v1
        with:
          bump: ${{ needs.release-prerequisites.outputs.bump }}
          github_token: ${{ secrets.GITHUB_TOKEN }}